# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mentathiel/Documents/Faks/IV/azrs/RGChess/RG136-chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mentathiel/Documents/Faks/IV/azrs/RGChess/RG136-chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mentathiel/Documents/Faks/IV/azrs/RGChess/RG136-chess/CMakeFiles /home/mentathiel/Documents/Faks/IV/azrs/RGChess/RG136-chess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mentathiel/Documents/Faks/IV/azrs/RGChess/RG136-chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lchess

# Build rule for target.
lchess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lchess
.PHONY : lchess

# fast build rule for target.
lchess/fast:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/build
.PHONY : lchess/fast

#=============================================================================
# Target rules for targets named chess

# Build rule for target.
chess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess
.PHONY : chess

# fast build rule for target.
chess/fast:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/build
.PHONY : chess/fast

Bishop.o: Bishop.cc.o

.PHONY : Bishop.o

# target to build an object file
Bishop.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Bishop.cc.o
.PHONY : Bishop.cc.o

Bishop.i: Bishop.cc.i

.PHONY : Bishop.i

# target to preprocess a source file
Bishop.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Bishop.cc.i
.PHONY : Bishop.cc.i

Bishop.s: Bishop.cc.s

.PHONY : Bishop.s

# target to generate assembly for a file
Bishop.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Bishop.cc.s
.PHONY : Bishop.cc.s

ChessPiece.o: ChessPiece.cc.o

.PHONY : ChessPiece.o

# target to build an object file
ChessPiece.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/ChessPiece.cc.o
.PHONY : ChessPiece.cc.o

ChessPiece.i: ChessPiece.cc.i

.PHONY : ChessPiece.i

# target to preprocess a source file
ChessPiece.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/ChessPiece.cc.i
.PHONY : ChessPiece.cc.i

ChessPiece.s: ChessPiece.cc.s

.PHONY : ChessPiece.s

# target to generate assembly for a file
ChessPiece.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/ChessPiece.cc.s
.PHONY : ChessPiece.cc.s

Chessboard.o: Chessboard.cc.o

.PHONY : Chessboard.o

# target to build an object file
Chessboard.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Chessboard.cc.o
.PHONY : Chessboard.cc.o

Chessboard.i: Chessboard.cc.i

.PHONY : Chessboard.i

# target to preprocess a source file
Chessboard.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Chessboard.cc.i
.PHONY : Chessboard.cc.i

Chessboard.s: Chessboard.cc.s

.PHONY : Chessboard.s

# target to generate assembly for a file
Chessboard.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Chessboard.cc.s
.PHONY : Chessboard.cc.s

Field.o: Field.cc.o

.PHONY : Field.o

# target to build an object file
Field.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Field.cc.o
.PHONY : Field.cc.o

Field.i: Field.cc.i

.PHONY : Field.i

# target to preprocess a source file
Field.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Field.cc.i
.PHONY : Field.cc.i

Field.s: Field.cc.s

.PHONY : Field.s

# target to generate assembly for a file
Field.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Field.cc.s
.PHONY : Field.cc.s

Game.o: Game.cc.o

.PHONY : Game.o

# target to build an object file
Game.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Game.cc.o
.PHONY : Game.cc.o

Game.i: Game.cc.i

.PHONY : Game.i

# target to preprocess a source file
Game.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Game.cc.i
.PHONY : Game.cc.i

Game.s: Game.cc.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Game.cc.s
.PHONY : Game.cc.s

King.o: King.cc.o

.PHONY : King.o

# target to build an object file
King.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/King.cc.o
.PHONY : King.cc.o

King.i: King.cc.i

.PHONY : King.i

# target to preprocess a source file
King.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/King.cc.i
.PHONY : King.cc.i

King.s: King.cc.s

.PHONY : King.s

# target to generate assembly for a file
King.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/King.cc.s
.PHONY : King.cc.s

Knight.o: Knight.cc.o

.PHONY : Knight.o

# target to build an object file
Knight.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Knight.cc.o
.PHONY : Knight.cc.o

Knight.i: Knight.cc.i

.PHONY : Knight.i

# target to preprocess a source file
Knight.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Knight.cc.i
.PHONY : Knight.cc.i

Knight.s: Knight.cc.s

.PHONY : Knight.s

# target to generate assembly for a file
Knight.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Knight.cc.s
.PHONY : Knight.cc.s

Move.o: Move.cc.o

.PHONY : Move.o

# target to build an object file
Move.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Move.cc.o
.PHONY : Move.cc.o

Move.i: Move.cc.i

.PHONY : Move.i

# target to preprocess a source file
Move.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Move.cc.i
.PHONY : Move.cc.i

Move.s: Move.cc.s

.PHONY : Move.s

# target to generate assembly for a file
Move.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Move.cc.s
.PHONY : Move.cc.s

ObjHandler.o: ObjHandler.cc.o

.PHONY : ObjHandler.o

# target to build an object file
ObjHandler.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/ObjHandler.cc.o
.PHONY : ObjHandler.cc.o

ObjHandler.i: ObjHandler.cc.i

.PHONY : ObjHandler.i

# target to preprocess a source file
ObjHandler.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/ObjHandler.cc.i
.PHONY : ObjHandler.cc.i

ObjHandler.s: ObjHandler.cc.s

.PHONY : ObjHandler.s

# target to generate assembly for a file
ObjHandler.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/ObjHandler.cc.s
.PHONY : ObjHandler.cc.s

Pawn.o: Pawn.cc.o

.PHONY : Pawn.o

# target to build an object file
Pawn.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Pawn.cc.o
.PHONY : Pawn.cc.o

Pawn.i: Pawn.cc.i

.PHONY : Pawn.i

# target to preprocess a source file
Pawn.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Pawn.cc.i
.PHONY : Pawn.cc.i

Pawn.s: Pawn.cc.s

.PHONY : Pawn.s

# target to generate assembly for a file
Pawn.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Pawn.cc.s
.PHONY : Pawn.cc.s

Queen.o: Queen.cc.o

.PHONY : Queen.o

# target to build an object file
Queen.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Queen.cc.o
.PHONY : Queen.cc.o

Queen.i: Queen.cc.i

.PHONY : Queen.i

# target to preprocess a source file
Queen.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Queen.cc.i
.PHONY : Queen.cc.i

Queen.s: Queen.cc.s

.PHONY : Queen.s

# target to generate assembly for a file
Queen.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Queen.cc.s
.PHONY : Queen.cc.s

Rook.o: Rook.cc.o

.PHONY : Rook.o

# target to build an object file
Rook.cc.o:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Rook.cc.o
.PHONY : Rook.cc.o

Rook.i: Rook.cc.i

.PHONY : Rook.i

# target to preprocess a source file
Rook.cc.i:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Rook.cc.i
.PHONY : Rook.cc.i

Rook.s: Rook.cc.s

.PHONY : Rook.s

# target to generate assembly for a file
Rook.cc.s:
	$(MAKE) -f CMakeFiles/lchess.dir/build.make CMakeFiles/lchess.dir/Rook.cc.s
.PHONY : Rook.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lchess"
	@echo "... chess"
	@echo "... Bishop.o"
	@echo "... Bishop.i"
	@echo "... Bishop.s"
	@echo "... ChessPiece.o"
	@echo "... ChessPiece.i"
	@echo "... ChessPiece.s"
	@echo "... Chessboard.o"
	@echo "... Chessboard.i"
	@echo "... Chessboard.s"
	@echo "... Field.o"
	@echo "... Field.i"
	@echo "... Field.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... King.o"
	@echo "... King.i"
	@echo "... King.s"
	@echo "... Knight.o"
	@echo "... Knight.i"
	@echo "... Knight.s"
	@echo "... Move.o"
	@echo "... Move.i"
	@echo "... Move.s"
	@echo "... ObjHandler.o"
	@echo "... ObjHandler.i"
	@echo "... ObjHandler.s"
	@echo "... Pawn.o"
	@echo "... Pawn.i"
	@echo "... Pawn.s"
	@echo "... Queen.o"
	@echo "... Queen.i"
	@echo "... Queen.s"
	@echo "... Rook.o"
	@echo "... Rook.i"
	@echo "... Rook.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

